# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5ChatApp1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift5ChatApp1

  target 'Swift5ChatApp1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'lottie-ios'
  pod 'ChameleonFramework'

end
